import Navbar from "@/components/ui/navbar/Navbar";
import "./globals.css";
import Footer from "@/components/ui/footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir='rtl'>
      <body
      >
        <Navbar/>
        <main>
        {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
